// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    KdyAudio: typeof import('./../../src/components/kdy-audio/kdy-audio.vue')['default']
    KdyBottomPlay: typeof import('./../../src/components/kdy-bottom-play/kdy-bottom-play.vue')['default']
    KdySearch: typeof import('./../../src/components/kdy-search/kdy-search.vue')['default']
    KdySidebar: typeof import('./../../src/components/kdy-sidebar/kdy-sidebar.vue')['default']
    KdyTabbar: typeof import('./../../src/components/kdy-tabbar/kdy-tabbar.vue')['default']
    KdyTransition: typeof import('./../../src/components/kdy-transition/kdy-transition.vue')['default']
    Ripple: typeof import('@varlet/ui')['_RippleComponent']
    RowSongList: typeof import('./../../src/components/row-song-list/row-song-list.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
  }
}

export { }
