// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EnterTo: typeof import('@varlet/ui')['_EnterToComponent']
    KdySearch: typeof import('./../../src/components/kdy-search/kdy-search.vue')['default']
    KdyTabbar: typeof import('./../../src/components/kdy-tabbar/kdy-tabbar.vue')['default']
    KdyTransition: typeof import('./../../src/components/kdy-transition/kdy-transition.vue')['default']
    RowSongList: typeof import('./../../src/components/row-song-list/row-song-list.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
  }
}

export { }
