// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    KdySearch: typeof import('./../../src/components/kdy-search/kdy-search.vue')['default']
    KdyTabbar: typeof import('./../../src/components/kdy-tabbar/kdy-tabbar.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
  }
}

export { }
